# Generated by Django 4.2.13 on 2024-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='teamA',
            new_name='Blue',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='teamB',
            new_name='Green',
        ),
        migrations.AddField(
            model_name='score',
            name='Orange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='Red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='Yellow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='last_updated',
            field=models.DateTimeField(default=0),
        ),
    ]
